font_path: "MesloLGLDZNerdFont-Bold.ttf"
width: 1536
height: 960
background:
  image: ""
  # solid: "0,255,0,40"
  gradient:
    x0: 0 
    y0: 200
    x1: 0
    y1: 960
    start_color: "0,0,50,255"
    end_color: "0,0,0,255"
layout:
  frame_padding_x: 50
  frame_padding_y: 20
frame_style:
  stroke: 1.0
  title_font-size: 32.0
  content_font-size: 15.0
  title_padding: 10.0
  content_padding: 10.0
frames:
  Vim0:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
  Vim 1:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
  Vim 2:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
  Vim3:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
  Vim6:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - aaaaaaaaaaaaaaaone more for good measureone more for good measure
  Vim5:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
  Vim4:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
