background:
  gradient:
    end_color: 0,0,0,255
    start_color: 0,0,50,255
    x0: 0
    x1: 0
    y0: 200
    y1: 960
  image: ""
debug: false
font_path: MesloLGLDZNerdFont-Bold.ttf
frame_style:
  content_font-size: 28 
  content_padding: 10
  stroke: 1
  title_font-size: 40
  title_padding: 10
frames:
  aerospace-main:
  - 'alt-X: workspace X'
  - 'alt-shift-k: move up'
  - 'alt-shift-j: move down'
  - 'alt-shift-h: move left'
  - 'alt-shift-l: move right'
  - ""
  - --Focus--
  - 'alt-k: focus up'
  - 'alt-j: focus down'
  - 'alt-h: focus left'
  - 'alt-l: focus right'
  - ""
  - --Workspaces--
  - 'alt-n: move-workspace-to-monitor next'
  - 'alt-p: move-workspace-to-monitor prev'
  - 'alt-shift-x: move-node-to-workspace X'
  - 'alt-tab: workspace-back-and-forth'
  - ""
  - --Layout--
  - 'alt-shift-equal: resize smart +50'
  - 'alt-shift-minus: resize smart -50'
  - 'alt-comma: layout accordion horizontal vertical'
  - 'alt-slash: layout tiles horizontal vertical'
  - ""
  - --Other--
  - 'alt-shift-semicolon: mode service'
  aerospace-service:
  - 'esc: reload-config; mode main'
  - 'r: flatten-workspace-tree; mode main'
  - 'f: layout floating tiling; mode main'
  - 'up: volume up'
  - 'down: volume down'
  - 'shift-down: volume set 0; mode main'
  - 'alt-shift-k: join-with up; mode main'
  - 'alt-shift-j: join-with down; mode main'
  - 'alt-shift-h: join-with left; mode main'
  - 'alt-shift-l: join-with right; mode main'
  - 'backspace: close-all-windows-but-current; mode main'
  nvim-debugger:
  - 'n <Space>db: Toggle DAP UI'
  - 'n <Space>bp: Toggle breakpoint'
  - 'n <Space>si: Step into'
  - 'n <Space>so: Step over'
  - 'n <Space>sr: Step return'
  - 'n <Space>dc: Continue'
  - 'n <Space>dr: Open REPL'
  - 'n <Space>dl: Run last'
  nvim-diagnostics:
  - 'n ]d: Jump to the next diagnostic'
  - 'n [d: Jump to the previous diagnostic'
  - 'n <C-W><C-D>: Show diagnostics under the cursor'
  - 'n <C-W>d: Show diagnostics under the cursor'
  - ''
  - '--Trouble--'
  - 'n [t: Go to next Trouble item'
  - 'n <Space>tt: Toggle Trouble diagnostics'
  - 'n ]t: Go to previous Trouble item'
  nvim-finding-files:
  - '--Telescope--'
  - 'n <Space>fg: Telescope live grep'
  - 'n <Space>ff: Telescope find files'
  - 'n <Space>lg: Local live grep'
  - 'n <Space>fgg: Telescope finds files in git'
  - ''
  - '--Oil--'
  - 'n <Space>pv: Open oil in split window'
  - 'n <Space>pvo: Open Oil'
  - ''
  - '--Harpoon--'
  - 'n <Space>a: Add file to harpoon'
  - 'n <C-E>: Toggle Harpoon menu'
  nvim-surround:
  - 'x S: Add a surrounding pair around a visual selection'
  - 'n ds: Delete a surrounding pair'
  - 'n cs: Change a surrounding pair'
  - 'n yS: Add a surrounding pair around a motion, on new lines (normal mode)'
  - 'n yss: Add a surrounding pair around the current line (normal mode)'
  - 'n ySS: Add a surrounding pair around the current line, on new lines (normal mode)'
  - 'x gS: Add a surrounding pair around a visual selection, on new lines'
  - 'n ys: Add a surrounding pair around a motion (normal mode)'
  - 'n cS: Change a surrounding pair, putting replacements on new lines'
  nvim-other:
  - 'n <Space>gd: Open definition in new tab'

  - 'n <Space>p: Paste from system clipboard'
  - 'n <Space>yy: Yank line to system clipboard'
  - 'n <Space>y: Yank to system clipboard'
  
  - 'n gcc: Toggle comment line'
  - 'n gc: Toggle comment'

  - 'n gx: Opens filepath or URI under cursor with the system handler (file explorer,
    web browser, …)'

  - 'n <Space>ai: Toggle Copilot Chat'
  - 'n <Space>mm: Open minimap'
  - 'n <Space>gs: Open Git status'

  tmux-other:
  - 'C-Space s: Choose a session from a list'
  - 'C-Space ?: List key bindings'
  - 'C-Space [: Enter copy mode'
  - 'C-Space d: Detach the current client'
  tmux-panes:
  - --Navigation--
  - 'C-Space f: Search for a pane'
  - 'C-Space Up: Select the pane above the active pane'
  - 'C-Space Down: Select the pane below the active pane'
  - 'C-Space Right: Select the pane to the right of the active pane'
  - 'C-Space Left: Select the pane to the left of the active pane'
  - 'C-Space ;: Move to the previously active pane'
  - ""
  - --Resize--
  - 'C-Space C-Up: Resize the pane up'
  - 'C-Space C-Down: Resize the pane down'
  - 'C-Space C-Right: Resize the pane right'
  - 'C-Space C-Left: Resize the pane left'
  - 'C-Space M-Up: Resize the pane up by 5'
  - 'C-Space M-Down: Resize the pane down by 5'
  - 'C-Space M-Right: Resize the pane right by 5'
  - 'C-Space M-Left: Resize the pane left by 5'
  - ""
  - --Positions--
  - 'C-Space z: Zoom the active pane'
  - 'C-Space E: Spread panes out evenly'
  - 'C-Space {: Swap the active pane with the pane above'
  - 'C-Space }: Swap the active pane with the pane below'
  - 'C-Space Space: Select next layout'
  tmux-windows:
  - 'C-Space w: Choose a window from a list'
  - 'C-Space c: Create window'
  - 'C-Space n: Select the next window'
  - 'C-Space p: Select the previous window'
  - 'C-Space <number>: Select window <number>'
  - 'C-Space .: Move the current window'
  - 'C-Space ,: Rename current window'
  - 'C-Space !: Break pane to a new window'
height: 2160
layout:
  frame_padding_x: 50
  frame_padding_y: 60
width: 3840
