font_path: "MesloLGLDZNerdFont-Bold.ttf"
width: 1536
height: 960
layout:
  frame_padding_x: 50
  frame_padding_y: 20
frame_style:
  stroke: 1.0
  title_font-size: 32.0
  content_font-size: 15.0
  title_padding: 10.0
  content_padding: 10.0
frames:
  Vim0:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
  Vim 1:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
  Vim 2:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
  Vim3:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
  Vim6:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - aaaaaaaaaaaaaaaone more for good measureone more for good measure
  Vim5:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
  Vim4:
    - vim 1 dog
    - here's another one 
    - one more for good measure
    - one more for good measure
    - one more for good measure
    - one more for good measure
